#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/infinix/X670

PRODUCT_COPY_FILES += \
    vendor/infinix/X670/proprietary/vendor/app/mcRegistry/020f0000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/020f0000000000000000000000000000.drbin \
    vendor/infinix/X670/proprietary/vendor/app/mcRegistry/020f0000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/020f0000000000000000000000000000.tlbin \
    vendor/infinix/X670/proprietary/vendor/app/mcRegistry/030c0000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/030c0000000000000000000000000000.drbin \
    vendor/infinix/X670/proprietary/vendor/app/mcRegistry/030c0000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/030c0000000000000000000000000000.tlbin \
    vendor/infinix/X670/proprietary/vendor/app/mcRegistry/05120000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05120000000000000000000000000000.drbin \
    vendor/infinix/X670/proprietary/vendor/app/mcRegistry/05120000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05120000000000000000000000000000.tlbin \
    vendor/infinix/X670/proprietary/vendor/app/mcRegistry/05120000000000000000000000000001.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05120000000000000000000000000001.drbin \
    vendor/infinix/X670/proprietary/vendor/app/mcRegistry/05120000000000000000000000000001.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05120000000000000000000000000001.tlbin \
    vendor/infinix/X670/proprietary/vendor/app/mcRegistry/06090000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/06090000000000000000000000000000.drbin \
    vendor/infinix/X670/proprietary/vendor/app/mcRegistry/06090000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/06090000000000000000000000000000.tlbin \
    vendor/infinix/X670/proprietary/vendor/app/mcRegistry/0706000000000000000000000000004d.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/0706000000000000000000000000004d.tlbin \
    vendor/infinix/X670/proprietary/vendor/app/mcRegistry/07061000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07061000000000000000000000000000.tlbin \
    vendor/infinix/X670/proprietary/vendor/app/mcRegistry/07170000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07170000000000000000000000000000.drbin \
    vendor/infinix/X670/proprietary/vendor/app/mcRegistry/07170000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07170000000000000000000000000000.tlbin \
    vendor/infinix/X670/proprietary/vendor/app/mcRegistry/08030000000000000000000000000000.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08030000000000000000000000000000.tabin \
    vendor/infinix/X670/proprietary/vendor/app/mcRegistry/08040000000000000000000000003419.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08040000000000000000000000003419.tabin \
    vendor/infinix/X670/proprietary/vendor/app/mcRegistry/08050000000000000000000000003419.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08050000000000000000000000003419.drbin \
    vendor/infinix/X670/proprietary/vendor/app/mcRegistry/08050000000000000000000000003419.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08050000000000000000000000003419.tlbin \
    vendor/infinix/X670/proprietary/vendor/app/mcRegistry/08110000000000000000000000000000.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08110000000000000000000000000000.tabin \
    vendor/infinix/X670/proprietary/vendor/app/mcRegistry/40188311faf343488db888ad39496f9a.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/40188311faf343488db888ad39496f9a.drbin \
    vendor/infinix/X670/proprietary/vendor/app/mcRegistry/40188311faf343488db888ad39496f9a.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/40188311faf343488db888ad39496f9a.tlbin \
    vendor/infinix/X670/proprietary/vendor/app/mcRegistry/5020170115e016302017012521300000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/5020170115e016302017012521300000.drbin \
    vendor/infinix/X670/proprietary/vendor/app/mcRegistry/5020170115e016302017012521300000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/5020170115e016302017012521300000.tlbin \
    vendor/infinix/X670/proprietary/vendor/app/mcRegistry/85fbf4ccc2fd4a32922a4e90c56179de.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/85fbf4ccc2fd4a32922a4e90c56179de.tabin \
    vendor/infinix/X670/proprietary/vendor/app/mcRegistry/abcd270ea5c44c58bcd3384a2fa2539e.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/abcd270ea5c44c58bcd3384a2fa2539e.tabin \
    vendor/infinix/X670/proprietary/vendor/app/mcRegistry/ce4550edbcb1662566b006ebcb303050.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ce4550edbcb1662566b006ebcb303050.tabin \
    vendor/infinix/X670/proprietary/vendor/app/mcRegistry/df1edda8627911e980ae507b9d9a7e7d.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/df1edda8627911e980ae507b9d9a7e7d.tabin \
    vendor/infinix/X670/proprietary/vendor/app/mcRegistry/e97c270ea5c44c58bcd3384a2fa2539e.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/e97c270ea5c44c58bcd3384a2fa2539e.tabin \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/M_Segment_DoubleLoss_V1.model:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/M_Segment_DoubleLoss_V1.model \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/Transsion_Segment_Pre.mnn:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/Transsion_Segment_Pre.mnn \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/animal_human_landmark_fp16.mnn:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/animal_human_landmark_fp16.mnn \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/capture_sky.mnn:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/capture_sky.mnn \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/eyes_detect_model:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/eyes_detect_model \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/facerecheck.bin:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/facerecheck.bin \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/facerecheck.param:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/facerecheck.param \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/facesr_hd_composite_ref_4.1.15_mtkg96_ppl3_ocl.model:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/facesr_hd_composite_ref_4.1.15_mtkg96_ppl3_ocl.model \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/lightforgender_addindian_tf113_test5.tflite:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/lightforgender_addindian_tf113_test5.tflite \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/lightforgender_addindian_tf113_test5_converted.mnn:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/lightforgender_addindian_tf113_test5_converted.mnn \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/lightforgenderandage_tf113_test4.tflite:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/lightforgenderandage_tf113_test4.tflite \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/lightforgenderandage_tf113_test4_converted.mnn:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/lightforgenderandage_tf113_test4_converted.mnn \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/lut_aurora.png:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/lut_aurora.png \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/lut_dusk.png:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/lut_dusk.png \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/lut_meteor.png:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/lut_meteor.png \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/lut_moon.png:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/lut_moon.png \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/lut_rainbow.png:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/lut_rainbow.png \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/lut_river.png:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/lut_river.png \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/lut_starry.png:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/lut_starry.png \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/lut_startrail.png:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/lut_startrail.png \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/lut_sunset.png:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/lut_sunset.png \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/lut_sunset2.png:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/lut_sunset2.png \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/lut_sunshine.png:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/lut_sunshine.png \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/lut_sunshine2.png:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/lut_sunshine2.png \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/megii_dualcam/cache_data:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/megii_dualcam/cache_data \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/megii_dualcam/capture_cache:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/megii_dualcam/capture_cache \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/megii_dualcam/capture_model:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/megii_dualcam/capture_model \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/megii_dualcam/capture_policy:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/megii_dualcam/capture_policy \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/megii_dualcam/dof_mecp.bin:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/megii_dualcam/dof_mecp.bin \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/megii_dualcam/preview_cache:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/megii_dualcam/preview_cache \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/megii_dualcam/preview_model:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/megii_dualcam/preview_model \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/megii_dualcam/preview_policy:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/megii_dualcam/preview_policy \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/meishefilter/Paris06.mslut:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/meishefilter/Paris06.mslut \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/meishefilter/abao.mslut:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/meishefilter/abao.mslut \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/meishefilter/heijin01.mslut:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/meishefilter/heijin01.mslut \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/meishefilter/heijin02.mslut:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/meishefilter/heijin02.mslut \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/meishefilter/landiao.mslut:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/meishefilter/landiao.mslut \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/meishefilter/saibo.mslut:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/meishefilter/saibo.mslut \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/meishefilter/youhua.mslut:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/meishefilter/youhua.mslut \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/preview_sky.mnn:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/preview_sky.mnn \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/preview_sky_aurora.jpg:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/preview_sky_aurora.jpg \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/preview_sky_dusk.jpg:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/preview_sky_dusk.jpg \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/preview_sky_meteor.jpg:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/preview_sky_meteor.jpg \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/preview_sky_moon.jpg:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/preview_sky_moon.jpg \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/preview_sky_rainbow.jpg:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/preview_sky_rainbow.jpg \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/preview_sky_river.jpg:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/preview_sky_river.jpg \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/preview_sky_starry.jpg:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/preview_sky_starry.jpg \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/preview_sky_startrail.jpg:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/preview_sky_startrail.jpg \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/preview_sky_sunset.jpg:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/preview_sky_sunset.jpg \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/preview_sky_sunset2.jpg:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/preview_sky_sunset2.jpg \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/preview_sky_sunshine.jpg:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/preview_sky_sunshine.jpg \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/preview_sky_sunshine2.jpg:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/preview_sky_sunshine2.jpg \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/rgbw_fusion_global_config.xml:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/rgbw_fusion_global_config.xml \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/scene.tflite:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/scene.tflite \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/segment.tflite:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/segment.tflite \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/segmentPre.tflite:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/segmentPre.tflite \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/sky_aurora.jpg:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/sky_aurora.jpg \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/sky_dusk.jpg:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/sky_dusk.jpg \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/sky_meteor.jpg:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/sky_meteor.jpg \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/sky_moon.jpg:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/sky_moon.jpg \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/sky_rainbow.jpg:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/sky_rainbow.jpg \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/sky_river.jpg:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/sky_river.jpg \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/sky_starry.jpg:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/sky_starry.jpg \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/sky_startrail.jpg:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/sky_startrail.jpg \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/sky_sunset.jpg:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/sky_sunset.jpg \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/sky_sunset2.jpg:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/sky_sunset2.jpg \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/sky_sunshine.jpg:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/sky_sunshine.jpg \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/sky_sunshine2.jpg:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/sky_sunshine2.jpg \
    vendor/infinix/X670/proprietary/vendor/data/camera/model/sr_params.xml:$(TARGET_COPY_OUT_VENDOR)/data/camera/model/sr_params.xml \
    vendor/infinix/X670/proprietary/vendor/data/camera/watermark/watermark_1280x720.nv21:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_1280x720.nv21 \
    vendor/infinix/X670/proprietary/vendor/data/camera/watermark/watermark_1280x720.yuyv:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_1280x720.yuyv \
    vendor/infinix/X670/proprietary/vendor/data/camera/watermark/watermark_1920x1080.nv21:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_1920x1080.nv21 \
    vendor/infinix/X670/proprietary/vendor/data/camera/watermark/watermark_1920x1080.yuyv:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_1920x1080.yuyv \
    vendor/infinix/X670/proprietary/vendor/data/camera/watermark/watermark_2560x1440.nv21:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_2560x1440.nv21 \
    vendor/infinix/X670/proprietary/vendor/data/camera/watermark/watermark_2560x1440.yuyv:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_2560x1440.yuyv \
    vendor/infinix/X670/proprietary/vendor/data/camera/watermark/watermark_3840x2160.nv21:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_3840x2160.nv21 \
    vendor/infinix/X670/proprietary/vendor/data/camera/watermark/watermark_3840x2160.yuyv:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_3840x2160.yuyv \
    vendor/infinix/X670/proprietary/vendor/data/camera/watermark/watermark_640x480.nv21:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_640x480.nv21 \
    vendor/infinix/X670/proprietary/vendor/data/camera/watermark/watermark_640x480.yuyv:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_640x480.yuyv \
    vendor/infinix/X670/proprietary/vendor/data/camera/watermark/watermark_config:$(TARGET_COPY_OUT_VENDOR)/data/camera/watermark/watermark_config \
    vendor/infinix/X670/proprietary/vendor/etc/AbnormalDisplayLog_dynamic.xml:$(TARGET_COPY_OUT_VENDOR)/etc/AbnormalDisplayLog_dynamic.xml \
    vendor/infinix/X670/proprietary/vendor/etc/AudioLog_dynamic.xml:$(TARGET_COPY_OUT_VENDOR)/etc/AudioLog_dynamic.xml \
    vendor/infinix/X670/proprietary/vendor/etc/MNL_Config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/MNL_Config.xml \
    vendor/infinix/X670/proprietary/vendor/etc/VideoLog_dynamic.xml:$(TARGET_COPY_OUT_VENDOR)/etc/VideoLog_dynamic.xml \
    vendor/infinix/X670/proprietary/vendor/etc/anc_siq/cache_hi1631q_17201701_front_g9xb:$(TARGET_COPY_OUT_VENDOR)/etc/anc_siq/cache_hi1631q_17201701_front_g9xb \
    vendor/infinix/X670/proprietary/vendor/etc/anc_siq/cache_s5kjn1_17201711_back_g9xb:$(TARGET_COPY_OUT_VENDOR)/etc/anc_siq/cache_s5kjn1_17201711_back_g9xb \
    vendor/infinix/X670/proprietary/vendor/etc/anc_siq/dgain_mask_hi1631q_17201701_front_g9xb.bin:$(TARGET_COPY_OUT_VENDOR)/etc/anc_siq/dgain_mask_hi1631q_17201701_front_g9xb.bin \
    vendor/infinix/X670/proprietary/vendor/etc/anc_siq/dgain_mask_s5kjn1_17201711_back_g9xb.bin:$(TARGET_COPY_OUT_VENDOR)/etc/anc_siq/dgain_mask_s5kjn1_17201711_back_g9xb.bin \
    vendor/infinix/X670/proprietary/vendor/etc/anc_siq/siq_ocl_cache_hi1631q_17201701_front_g9xb:$(TARGET_COPY_OUT_VENDOR)/etc/anc_siq/siq_ocl_cache_hi1631q_17201701_front_g9xb \
    vendor/infinix/X670/proprietary/vendor/etc/anc_siq/siq_ocl_cache_s5kjn1_17201711_back_g9xb:$(TARGET_COPY_OUT_VENDOR)/etc/anc_siq/siq_ocl_cache_s5kjn1_17201711_back_g9xb \
    vendor/infinix/X670/proprietary/vendor/etc/anc_siq/superiq_model_hi1631q_17201701_front_g9xb:$(TARGET_COPY_OUT_VENDOR)/etc/anc_siq/superiq_model_hi1631q_17201701_front_g9xb \
    vendor/infinix/X670/proprietary/vendor/etc/anc_siq/superiq_model_s5kjn1_17201711_back_g9xb:$(TARGET_COPY_OUT_VENDOR)/etc/anc_siq/superiq_model_s5kjn1_17201711_back_g9xb \
    vendor/infinix/X670/proprietary/vendor/etc/apdb/APDB_MT6785_S01__W2317:$(TARGET_COPY_OUT_VENDOR)/etc/apdb/APDB_MT6785_S01__W2317 \
    vendor/infinix/X670/proprietary/vendor/etc/apdb/APDB_MT6785_S01__W2317_ENUM:$(TARGET_COPY_OUT_VENDOR)/etc/apdb/APDB_MT6785_S01__W2317_ENUM \
    vendor/infinix/X670/proprietary/vendor/etc/armnn_app.config:$(TARGET_COPY_OUT_VENDOR)/etc/armnn_app.config \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/AudioParamOptions.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/AudioParamOptions.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/AudioParamOptions_vext.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/AudioParamOptions_vext.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/BtInfo_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/BtInfo_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/BtInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/BtInfo_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/CRSVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVolUI_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/CRSVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVolUI_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/CRSVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVol_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/CRSVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVol_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/HpImpedance_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/HpImpedance_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/HpImpedance_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/HpImpedance_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/MicInfo_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/MicInfo_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/MicInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/MicInfo_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/PlaybackACF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackACF_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/PlaybackACF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackACF_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/PlaybackDRC_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackDRC_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/PlaybackDRC_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackDRC_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/PlaybackHCF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackHCF_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/PlaybackHCF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackHCF_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/PlaybackVolAna_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolAna_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/PlaybackVolAna_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolAna_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/PlaybackVolDigi_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolDigi_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/PlaybackVolDigi_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolDigi_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/PlaybackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolUI_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/PlaybackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolUI_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/Playback_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/Playback_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_ParamTreeView.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/Playback_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/RecordDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordDMNR_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/RecordDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordDMNR_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/RecordFIR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordFIR_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/RecordFIR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordFIR_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/RecordUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordUI_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/RecordUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordUI_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/RecordVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVolUI_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/RecordVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVolUI_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/RecordVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVol_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/RecordVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVol_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/Record_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/Record_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_ParamTreeView.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/Record_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/RingbackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVolUI_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/RingbackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVolUI_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/RingbackVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVol_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/RingbackVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVol_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/SmartPa_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SmartPa_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/SmartPa_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SmartPa_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/SoundEnhancement_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SoundEnhancement_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/SoundEnhancement_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SoundEnhancement_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/SpeechDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechDMNR_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/SpeechDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechDMNR_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/SpeechEchoRef_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechEchoRef_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/SpeechEchoRef_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechEchoRef_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/SpeechGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechGeneral_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/SpeechGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechGeneral_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/SpeechMagiClarity_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechMagiClarity_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/SpeechMagiClarity_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechMagiClarity_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/SpeechNetwork_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechNetwork_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/SpeechNetwork_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechNetwork_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/SpeechUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechUI_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/SpeechUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechUI_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/SpeechVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVolUI_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/SpeechVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVolUI_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/SpeechVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVol_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/SpeechVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVol_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/Speech_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/Speech_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_ParamTreeView.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/Speech_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/USBCall_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBCall_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/USBCall_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBCall_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/USBDevice_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBDevice_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/USBDevice_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBDevice_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/Ultrasound_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Ultrasound_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/Ultrasound_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Ultrasound_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/UplinkConfiguration_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/UplinkConfiguration_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/UplinkConfiguration_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/UplinkConfiguration_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/VoIPDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPDMNR_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/VoIPDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPDMNR_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/VoIPGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPGeneral_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/VoIPGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPGeneral_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/VoIPUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPUI_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/VoIPUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPUI_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/VoIPVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVolUI_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/VoIPVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVolUI_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/VoIPVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVol_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/VoIPVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVol_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/VoIP_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/VoIP_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_ParamTreeView.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/VoIP_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/VoIPv2DMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2DMNR_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/VoIPv2DMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2DMNR_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/VoIPv2General_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2General_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/VoIPv2General_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2General_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/VoIPv2UI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2UI_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/VoIPv2UI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2UI_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/VoIPv2_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/VoIPv2_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_ParamTreeView.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/VoIPv2_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/VoWDspAec_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWDspAec_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/VoWDspAec_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWDspAec_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/VoWEngineFeature_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWEngineFeature_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/VoWEngineFeature_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWEngineFeature_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/VoWHwVad_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWHwVad_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/VoWHwVad_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWHwVad_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/VoWMicSetting_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWMicSetting_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/VoWMicSetting_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWMicSetting_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/VoWVoiceCommand_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWVoiceCommand_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/VoWVoiceCommand_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWVoiceCommand_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/VolumeGainMapUL_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMapUL_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/VolumeGainMapUL_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMapUL_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/VolumeGainMap_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMap_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/VolumeGainMap_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMap_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/Volume_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Volume_AudioParam.xml \
    vendor/infinix/X670/proprietary/vendor/etc/audio_param/Volume_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Volume_ParamUnitDesc.xml \
    vendor/infinix/X670/proprietary/vendor/etc/ecc_list.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list.xml \
    vendor/infinix/X670/proprietary/vendor/etc/ecc_list_OP01.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP01.xml \
    vendor/infinix/X670/proprietary/vendor/etc/ecc_list_OP02.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP02.xml \
    vendor/infinix/X670/proprietary/vendor/etc/ecc_list_OP09.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP09.xml \
    vendor/infinix/X670/proprietary/vendor/etc/ecc_list_OP12.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP12.xml \
    vendor/infinix/X670/proprietary/vendor/etc/ecc_list_OP17.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP17.xml \
    vendor/infinix/X670/proprietary/vendor/etc/ecc_list_OP18.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP18.xml \
    vendor/infinix/X670/proprietary/vendor/etc/ecc_list_OP20.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP20.xml \
    vendor/infinix/X670/proprietary/vendor/etc/ecc_list_OP236.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP236.xml \
    vendor/infinix/X670/proprietary/vendor/etc/ecc_list_preference.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_preference.xml \
    vendor/infinix/X670/proprietary/vendor/etc/gnss/agps_profiles_conf2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/agps_profiles_conf2.xml \
    vendor/infinix/X670/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_Mexico.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_Mexico.xml \
    vendor/infinix/X670/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_US.xml \
    vendor/infinix/X670/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Peru.xml \
    vendor/infinix/X670/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Entel_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Entel_Peru.xml \
    vendor/infinix/X670/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_KDDI.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_KDDI.xml \
    vendor/infinix/X670/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_SK_Telecom.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_SK_Telecom.xml \
    vendor/infinix/X670/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_SoftBank.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_SoftBank.xml \
    vendor/infinix/X670/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Sprint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Sprint.xml \
    vendor/infinix/X670/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_T-Mobile_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_T-Mobile_US.xml \
    vendor/infinix/X670/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM1.xml \
    vendor/infinix/X670/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM2.xml \
    vendor/infinix/X670/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Verizon_Wireless.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Verizon_Wireless.xml \
    vendor/infinix/X670/proprietary/vendor/etc/init/android.hardware.drm@1.4-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.4-service.widevine.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/android.hardware.gnss-service.mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gnss-service.mediatek.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/android.hardware.graphics.allocator@4.0-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.graphics.allocator@4.0-service-mediatek.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/android.hardware.keymaster@4.1-service.trustonic.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@4.1-service.trustonic.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/android.hardware.media.c2@1.2-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.media.c2@1.2-mediatek.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/android.hardware.neuralnetworks@1.3-service-mtk-neuron.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.neuralnetworks@1.3-service-mtk-neuron.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/android.hardware.secure_element@1.2-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.secure_element@1.2-service-mediatek.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/android.hardware.usb@1.2-service-mediatekv2.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.usb@1.2-service-mediatekv2.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/camerahalserver.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/camerahalserver.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/fuelgauged_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fuelgauged_init.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/fuelgauged_nvram_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fuelgauged_nvram_init.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/gsm0710muxd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/gsm0710muxd.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/init.bip.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.bip.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/init.bt_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.bt_drv.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/init.cccimdinit.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccimdinit.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/init.cccirpcd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccirpcd.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/init.connfem.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.connfem.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/init.gps_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.gps_drv.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/init.md_apps.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.md_apps.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/init.thermal.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.thermal.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/init.thermal_manager.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.thermal_manager.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/init.thermalloadalgod.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.thermalloadalgod.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/init.volte_imcb.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_imcb.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/init.volte_imsm_93.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_imsm_93.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/init.volte_md_status.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_md_status.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/init.volte_stack.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_stack.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/init.volte_ua.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_ua.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/init.vtservice_hidl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vtservice_hidl.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/init.wfca.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wfca.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/init.wlan_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wlan_drv.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/init.wmt_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wmt_drv.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/init.wod.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wod.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/init.xcap.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.xcap.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/ipsec_mon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ipsec_mon.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/mtk_agpsd_p.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtk_agpsd_p.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/mtkrild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtkrild.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/muxreport.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/muxreport.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/netdagent.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/netdagent.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/nvram_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/nvram_daemon.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/tee.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/tee.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/tetheroffloadservice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/tetheroffloadservice.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/trustonic.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/trustonic.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/vendor.fpsensor.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.fpsensor.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/vendor.mediatek.hardware.keymaster_attestation@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.keymaster_attestation@1.1-service.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/vendor.mediatek.hardware.mmagent@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.mmagent@1.1-service.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/vendor.mediatek.hardware.mms@1.6-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.mms@1.6-service.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/vendor.mediatek.hardware.nvram@1.1-sevice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.nvram@1.1-sevice.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/vendor.mediatek.hardware.pq@2.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.pq@2.2-service.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/vendor.transsion.hardware.trancam.trancamserver@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.transsion.hardware.trancam.trancamserver@1.0-service.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/volte_clientapi_ua.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/volte_clientapi_ua.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/vpud.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vpud.rc \
    vendor/infinix/X670/proprietary/vendor/etc/init/wlan_assistant.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wlan_assistant.rc \
    vendor/infinix/X670/proprietary/vendor/etc/ipsec/ipsec.conf:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.conf \
    vendor/infinix/X670/proprietary/vendor/etc/ipsec/ssl/openssl.cnf:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ssl/openssl.cnf \
    vendor/infinix/X670/proprietary/vendor/etc/ipsec/strongswan.conf:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/strongswan.conf \
    vendor/infinix/X670/proprietary/vendor/etc/mpe.conf:$(TARGET_COPY_OUT_VENDOR)/etc/mpe.conf \
    vendor/infinix/X670/proprietary/vendor/etc/mtk_platform_codecs_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mtk_platform_codecs_config.xml \
    vendor/infinix/X670/proprietary/vendor/etc/slp_conf:$(TARGET_COPY_OUT_VENDOR)/etc/slp_conf \
    vendor/infinix/X670/proprietary/vendor/etc/smsdbvisitor.xml:$(TARGET_COPY_OUT_VENDOR)/etc/smsdbvisitor.xml \
    vendor/infinix/X670/proprietary/vendor/etc/special_pws_channel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/special_pws_channel.xml \
    vendor/infinix/X670/proprietary/vendor/etc/vendor-apns-conf.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vendor-apns-conf.xml \
    vendor/infinix/X670/proprietary/vendor/firmware/BT_FW.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/BT_FW.cfg \
    vendor/infinix/X670/proprietary/vendor/firmware/WIFI_RAM_CODE_soc2_2_2_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/WIFI_RAM_CODE_soc2_2_2_1.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/WIFI_RAM_CODE_soc2_2_2a_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/WIFI_RAM_CODE_soc2_2_2a_1.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/WMT_SOC.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/WMT_SOC.cfg \
    vendor/infinix/X670/proprietary/vendor/firmware/aw8622x_haptic.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_haptic.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/aw8622x_osc_rtp_12K_10s.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_osc_rtp_12K_10s.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/aw8622x_rtp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/aw8624_haptic.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8624_haptic.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/aw8624_osc_rtp_24K_5s.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8624_osc_rtp_24K_5s.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/aw8624_rtp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8624_rtp.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/aw8624_rtp_lighthouse.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8624_rtp_lighthouse.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/aw8624_rtp_silk.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8624_rtp_silk.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/aw87xxx_acf.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw87xxx_acf.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/awinic_params.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/awinic_params.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/fm_cust.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/fm_cust.cfg \
    vendor/infinix/X670/proprietary/vendor/firmware/fs1599.fsm:$(TARGET_COPY_OUT_VENDOR)/firmware/fs1599.fsm \
    vendor/infinix/X670/proprietary/vendor/firmware/gt9896s_cfg_6781v01_1080x2280.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6781v01_1080x2280.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/gt9896s_cfg_6781v01_1080x2300.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6781v01_1080x2300.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/gt9896s_cfg_6789v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6789v01.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/gt9896s_cfg_6833v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6833v01.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/gt9896s_cfg_6853v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6853v01.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/gt9896s_cfg_6855v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6855v01.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/gt9896s_cfg_6873v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6873v01.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/gt9896s_cfg_6877v01_1080x2280.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6877v01_1080x2280.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/gt9896s_cfg_6877v01_1080x2300.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6877v01_1080x2300.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/gt9896s_cfg_6879v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6879v01.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/gt9896s_cfg_6893v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6893v01.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/gt9896s_cfg_6893v02.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6893v02.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/gt9896s_cfg_6893v03.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6893v03.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/gt9896s_cfg_6893v04.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6893v04.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/gt9896s_cfg_6893v05.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6893v05.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/gt9896s_cfg_6895v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6895v01.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/gt9896s_cfg_6983v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6983v01.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/gt9896s_firmware_6781v01_1080x2280.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6781v01_1080x2280.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/gt9896s_firmware_6781v01_1080x2300.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6781v01_1080x2300.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/gt9896s_firmware_6789v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6789v01.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/gt9896s_firmware_6833v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6833v01.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/gt9896s_firmware_6853v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6853v01.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/gt9896s_firmware_6855v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6855v01.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/gt9896s_firmware_6873v00.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6873v00.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/gt9896s_firmware_6877v01_1080x2280.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6877v01_1080x2280.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/gt9896s_firmware_6877v01_1080x2300.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6877v01_1080x2300.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/gt9896s_firmware_6879v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6879v01.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/gt9896s_firmware_6893v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6893v01.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/gt9896s_firmware_6893v02.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6893v02.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/gt9896s_firmware_6893v03.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6893v03.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/gt9896s_firmware_6893v04.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6893v04.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/gt9896s_firmware_6893v05.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6893v05.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/gt9896s_firmware_6895v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6895v01.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/gt9896s_firmware_6983v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6983v01.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/lib3a.ccu:$(TARGET_COPY_OUT_VENDOR)/firmware/lib3a.ccu \
    vendor/infinix/X670/proprietary/vendor/firmware/mt6631_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6631_fm_v1_coeff.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/mt6631_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6631_fm_v1_patch.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/remoteproc_scp:$(TARGET_COPY_OUT_VENDOR)/firmware/remoteproc_scp \
    vendor/infinix/X670/proprietary/vendor/firmware/soc2_2_ram_bt_2_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_bt_2_1_hdr.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/soc2_2_ram_bt_2a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_bt_2a_1_hdr.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/soc2_2_ram_mcu_2_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_mcu_2_1_hdr.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/soc2_2_ram_mcu_2a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_mcu_2a_1_hdr.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/soc2_2_ram_wifi_2_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_wifi_2_1_hdr.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/soc2_2_ram_wifi_2a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_wifi_2a_1_hdr.bin \
    vendor/infinix/X670/proprietary/vendor/firmware/wifi.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi.cfg \
    vendor/infinix/X670/proprietary/vendor/lib/egl/egl.cfg:$(TARGET_COPY_OUT_VENDOR)/lib/egl/egl.cfg \
    vendor/infinix/X670/proprietary/vendor/lib/modules/app_defrag.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/app_defrag.ko \
    vendor/infinix/X670/proprietary/vendor/lib/modules/bt_drv_connac1x.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/bt_drv_connac1x.ko \
    vendor/infinix/X670/proprietary/vendor/lib/modules/connfem.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/connfem.ko \
    vendor/infinix/X670/proprietary/vendor/lib/modules/defrag_gc_ko.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/defrag_gc_ko.ko \
    vendor/infinix/X670/proprietary/vendor/lib/modules/dev_gc.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/dev_gc.ko \
    vendor/infinix/X670/proprietary/vendor/lib/modules/fmradio_drv_mt6631.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/fmradio_drv_mt6631.ko \
    vendor/infinix/X670/proprietary/vendor/lib/modules/fpsgo.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/fpsgo.ko \
    vendor/infinix/X670/proprietary/vendor/lib/modules/gps_drv.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/gps_drv.ko \
    vendor/infinix/X670/proprietary/vendor/lib/modules/met.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/met.ko \
    vendor/infinix/X670/proprietary/vendor/lib/modules/modules.alias:$(TARGET_COPY_OUT_VENDOR)/lib/modules/modules.alias \
    vendor/infinix/X670/proprietary/vendor/lib/modules/modules.dep:$(TARGET_COPY_OUT_VENDOR)/lib/modules/modules.dep \
    vendor/infinix/X670/proprietary/vendor/lib/modules/modules.load:$(TARGET_COPY_OUT_VENDOR)/lib/modules/modules.load \
    vendor/infinix/X670/proprietary/vendor/lib/modules/modules.softdep:$(TARGET_COPY_OUT_VENDOR)/lib/modules/modules.softdep \
    vendor/infinix/X670/proprietary/vendor/lib/modules/trace_mmstat.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/trace_mmstat.ko \
    vendor/infinix/X670/proprietary/vendor/lib/modules/tran_fre.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/tran_fre.ko \
    vendor/infinix/X670/proprietary/vendor/lib/modules/tran_gc_ko.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/tran_gc_ko.ko \
    vendor/infinix/X670/proprietary/vendor/lib/modules/udc_lib.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/udc_lib.ko \
    vendor/infinix/X670/proprietary/vendor/lib/modules/wlan_drv_gen4m.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/wlan_drv_gen4m.ko \
    vendor/infinix/X670/proprietary/vendor/lib/modules/wmt_chrdev_wifi.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/wmt_chrdev_wifi.ko \
    vendor/infinix/X670/proprietary/vendor/lib/modules/wmt_drv.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/wmt_drv.ko

PRODUCT_PACKAGES += \
    libem_aoltest_jni \
    libem_audio_jni \
    libem_support_jni \
    libem_wifi_jni \
    AVCSecureVdecCA \
    HEVCSecureVdecCA \
    VP9SecureVdecCA \
    audio.primary.mt6781 \
    audio.r_submix.mt6781 \
    kmsetkey.trustonic \
    vendor.mediatek.hardware.keymaster_attestation@1.1-impl \
    libAVCSecureVencCA \
    libMcClient \
    libMtkSpeechEnh \
    libTEECommon \
    libadpcmdec_mtk \
    libaedv \
    libaudio_param_parser-vnd \
    libaudiocompensationfilter_vendor \
    libaudiocompensationfilterc \
    libaudiocomponentengine_vendor \
    libaudiocomponentenginec \
    libaudiocustparam_vendor \
    libaudiodcrflt_vendor \
    libaudiofmtconv \
    libaudioloudc \
    libaudioprimarydevicehalifclient \
    libaudiotoolkit_vendor \
    libaurisysdemo \
    libbessound_hd_mtk_vendor \
    libblisrc32_vendor \
    libbwc \
    libcrypto-md \
    libcurl-md \
    libcustom_nvram \
    libcvsd_mtk \
    libdecrypt \
    libfile_op \
    libgz_gp_client \
    libgz_uree \
    libhevce_sb.ca7.android \
    libion_mtk \
    libion_ulit \
    libipsec_ims_shr \
    libladder \
    libmp3dec_mtk \
    libmtcloader \
    libmtkcutils \
    libmtklimiter_vendor \
    libmtkproperty \
    libmtkrillog \
    libmtkshifter_vendor \
    libnvram \
    libnvram_sec \
    libssl-md \
    libthha \
    libvcodec_oal \
    libvcodecdrv_header_stub \
    libverno \
    libmtk_drvb \
    vendor.mediatek.hardware.audio@6.1 \
    vendor.mediatek.hardware.audio@7.1 \
    vendor.mediatek.hardware.keymaster_attestation@1.0 \
    vendor.mediatek.hardware.keymaster_attestation@1.1 \
    awinic.audio.effect \
    libHEVCdec_sa.ca7.android \
    libfgauge_gm30 \
    libh264dec_customize \
    libh264dec_sa.ca7 \
    libh264dec_sd.ca7 \
    libh264dec_se.ca7 \
    libh264enc_sa.ca7 \
    libmp4enc_sa.ca7 \
    libmp4enc_xa.ca7 \
    libthermalalgo \
    libvcodec_utility \
    libvcodecdrv \
    libvolte_core_shr \
    libvolte_xdmc_shr \
    libvp8dec_sa.ca7 \
    libvp8enc_sa.ca7 \
    libvp9dec_sa.ca7 \
    libvpud_vcodec \
    vendor.mediatek.hardware.rcs@2.0 \
    APUWareUtilsServer \
    arm.graphics-V1-ndk_platform \
    libGLES_mali \
    libGLES_meow \
    libMEOW_data \
    libMEOW_gift \
    libMEOW_qt \
    libMEOW_trace \
    fake_serial_yuv_IdxMgr \
    fake_serial_yuv_tuning \
    gc02m1b_mipi_raw_IdxMgr \
    gc02m1b_mipi_raw_tuning \
    hi1631q_mipi_raw_IdxMgr \
    hi1631q_mipi_raw_tuning \
    android.hardware.camera.provider@2.6-impl-mediatek \
    android.hardware.gnss-impl-mediatek \
    android.hardware.gnss@2.1-impl-mediatek \
    android.hardware.graphics.allocator@4.0-impl-mediatek \
    android.hardware.graphics.mapper@4.0-impl-mediatek \
    android.hardware.sensors@2.X-subhal-mediatek \
    fingerprint.default \
    gps.default \
    gralloc.mt6781 \
    hwcomposer.mt6781 \
    libMcGatekeeper \
    libSoftGatekeeper \
    sensors.mt6781 \
    thermal.mt6781 \
    vendor.mediatek.hardware.camera.atms@1.0-impl \
    vendor.mediatek.hardware.camera.bgservice@1.1-impl \
    vendor.mediatek.hardware.camera.ccap@1.0-impl \
    vendor.mediatek.hardware.camera.isphal@1.0-impl \
    vendor.mediatek.hardware.camera.lomoeffect@1.0-impl \
    vendor.mediatek.hardware.camera.postproc@1.0-impl \
    vendor.mediatek.hardware.mms@1.6-impl \
    vendor.mediatek.hardware.nvram@1.1-impl \
    vendor.mediatek.hardware.pq@2.15-impl \
    vendor.mediatek.hardware.videotelephony@1.0-impl \
    vulkan.mali \
    lib3a.ae.core \
    lib3a.ae \
    lib3a.ae.stat \
    lib3a.af.assist \
    lib3a.af.assist.utils \
    lib3a.af.core \
    lib3a.af \
    lib3a.alsflicker \
    lib3a.awb.core \
    lib3a.ccudrv \
    lib3a.ccuif \
    lib3a.custom.ae \
    lib3a.dce \
    lib3a.flash \
    lib3a.flicker \
    lib3a.gma \
    lib3a.lce \
    lib3a.log \
    lib3a.n3d3a \
    lib3a.sensors.color \
    lib3a.sensors.flicker \
    libCamera_fakeserialyuv_E2EHDR_Preview \
    libCamera_fakeserialyuv_E2EHDR_Video \
    libCamera_fakeserialyuv_Face_Capture \
    libCamera_fakeserialyuv_Flash_Capture \
    libCamera_fakeserialyuv_HDR_Capture \
    libCamera_fakeserialyuv_HDR_Preview \
    libCamera_fakeserialyuv_HDR_Video \
    libCamera_fakeserialyuv_N3D_Capture \
    libCamera_fakeserialyuv_N3D_Preview \
    libCamera_fakeserialyuv_N3D_Video \
    libCamera_fakeserialyuv_P1_YUV \
    libCamera_fakeserialyuv_Scene_Capture \
    libCamera_fakeserialyuv_Scene_Capture_4cell \
    libCamera_fakeserialyuv_Scene_Preview \
    libCamera_fakeserialyuv_Scene_Preview_4k \
    libCamera_fakeserialyuv_Scene_Preview_ZSD_Flash \
    libCamera_fakeserialyuv_Video_1080 \
    libCamera_fakeserialyuv_Video_1080_60 \
    libCamera_fakeserialyuv_Video_4k \
    libCamera_gc02m1bmipiraw_Scene_Capture \
    libCamera_gc02m1bmipiraw_Scene_Preview \
    libCamera_hi1631qmipiraw_Beauty_capture \
    libCamera_hi1631qmipiraw_Capture_Zoom1 \
    libCamera_hi1631qmipiraw_Flash_Capture \
    libCamera_hi1631qmipiraw_HDR_MINUS_EV \
    libCamera_hi1631qmipiraw_NHDR_0EV \
    libCamera_hi1631qmipiraw_Preview_Zoom1 \
    libCamera_hi1631qmipiraw_Resolution \
    libCamera_hi1631qmipiraw_Resolution_zoom \
    libCamera_hi1631qmipiraw_Scene_Capture \
    libCamera_hi1631qmipiraw_Scene_Capture_ITS \
    libCamera_hi1631qmipiraw_Scene_Preview \
    libCamera_hi1631qmipiraw_ShortVideo \
    libCamera_hi1631qmipiraw_SuperNight \
    libCamera_hi1631qmipiraw_Video_1080 \
    libCamera_hi1631qmipiraw_Video_2k \
    libCamera_hi1631qmipiraw_Video_720 \
    libCamera_ov02b1bmipiraw_E2EHDR_Preview \
    libCamera_ov02b1bmipiraw_E2EHDR_Video \
    libCamera_ov02b1bmipiraw_Face_Capture \
    libCamera_ov02b1bmipiraw_Flash_Capture \
    libCamera_ov02b1bmipiraw_HDR_Capture \
    libCamera_ov02b1bmipiraw_HDR_Preview \
    libCamera_ov02b1bmipiraw_HDR_Video \
    libCamera_ov02b1bmipiraw_N3D_Capture \
    libCamera_ov02b1bmipiraw_N3D_Preview \
    libCamera_ov02b1bmipiraw_N3D_Video \
    libCamera_ov02b1bmipiraw_P1_YUV \
    libCamera_ov02b1bmipiraw_Scene_Capture \
    libCamera_ov02b1bmipiraw_Scene_Capture_4cell \
    libCamera_ov02b1bmipiraw_Scene_Preview \
    libCamera_ov02b1bmipiraw_Scene_Preview_4k \
    libCamera_ov02b1bmipiraw_Scene_Preview_ZSD_Flash \
    libCamera_ov02b1bmipiraw_Video_1080 \
    libCamera_ov02b1bmipiraw_Video_1080_60 \
    libCamera_ov02b1bmipiraw_Video_4k \
    libCamera_pblcgc02m1bmipiraw_Scene_Capture \
    libCamera_pblcgc02m1bmipiraw_Scene_Preview \
    libCamera_pblchi1631qmipiraw_Beauty_capture \
    libCamera_pblchi1631qmipiraw_Capture_Zoom1 \
    libCamera_pblchi1631qmipiraw_Flash_Capture \
    libCamera_pblchi1631qmipiraw_HDR_MINUS_EV \
    libCamera_pblchi1631qmipiraw_NHDR_0EV \
    libCamera_pblchi1631qmipiraw_Preview_Zoom1 \
    libCamera_pblchi1631qmipiraw_Resolution \
    libCamera_pblchi1631qmipiraw_Resolution_zoom \
    libCamera_pblchi1631qmipiraw_Scene_Capture \
    libCamera_pblchi1631qmipiraw_Scene_Capture_ITS \
    libCamera_pblchi1631qmipiraw_Scene_Preview \
    libCamera_pblchi1631qmipiraw_ShortVideo \
    libCamera_pblchi1631qmipiraw_SuperNight \
    libCamera_pblchi1631qmipiraw_Video_1080 \
    libCamera_pblchi1631qmipiraw_Video_2k \
    libCamera_pblchi1631qmipiraw_Video_720 \
    libCamera_pblcov02b1bmipiraw_E2EHDR_Preview \
    libCamera_pblcov02b1bmipiraw_E2EHDR_Video \
    libCamera_pblcov02b1bmipiraw_Face_Capture \
    libCamera_pblcov02b1bmipiraw_Flash_Capture \
    libCamera_pblcov02b1bmipiraw_HDR_Capture \
    libCamera_pblcov02b1bmipiraw_HDR_Preview \
    libCamera_pblcov02b1bmipiraw_HDR_Video \
    libCamera_pblcov02b1bmipiraw_N3D_Capture \
    libCamera_pblcov02b1bmipiraw_N3D_Preview \
    libCamera_pblcov02b1bmipiraw_N3D_Video \
    libCamera_pblcov02b1bmipiraw_P1_YUV \
    libCamera_pblcov02b1bmipiraw_Scene_Capture \
    libCamera_pblcov02b1bmipiraw_Scene_Capture_4cell \
    libCamera_pblcov02b1bmipiraw_Scene_Preview \
    libCamera_pblcov02b1bmipiraw_Scene_Preview_4k \
    libCamera_pblcov02b1bmipiraw_Scene_Preview_ZSD_Flash \
    libCamera_pblcov02b1bmipiraw_Video_1080 \
    libCamera_pblcov02b1bmipiraw_Video_1080_60 \
    libCamera_pblcov02b1bmipiraw_Video_4k \
    libCamera_pblcs5kjn1mipiraw_Boken_Capture \
    libCamera_pblcs5kjn1mipiraw_Capture_Zoom1 \
    libCamera_pblcs5kjn1mipiraw_Capture_Zoom2 \
    libCamera_pblcs5kjn1mipiraw_FaceBeauty \
    libCamera_pblcs5kjn1mipiraw_Flash_Capture \
    libCamera_pblcs5kjn1mipiraw_NHDR_0EV \
    libCamera_pblcs5kjn1mipiraw_Preview_Zoom1 \
    libCamera_pblcs5kjn1mipiraw_Preview_Zoom2 \
    libCamera_pblcs5kjn1mipiraw_Pro_scene \
    libCamera_pblcs5kjn1mipiraw_Resolution \
    libCamera_pblcs5kjn1mipiraw_Resolution_zoom \
    libCamera_pblcs5kjn1mipiraw_Scene_Capture \
    libCamera_pblcs5kjn1mipiraw_Scene_Capture_4cell \
    libCamera_pblcs5kjn1mipiraw_Scene_Preview \
    libCamera_pblcs5kjn1mipiraw_ShortVideo \
    libCamera_pblcs5kjn1mipiraw_SuperNight \
    libCamera_pblcs5kjn1mipiraw_Video \
    libCamera_pblcs5kjn1mipiraw_Video_120fps \
    libCamera_pblcs5kjn1mipiraw_Video_240fps \
    libCamera_pblcs5kjn1mipiraw_Video_EIS \
    libCamera_pblcs5kjn1mipiraw_Video_Zoom1 \
    libCamera_pblcs5kjn1mipiraw_Video_Zoom2 \
    libCamera_pbrogc02m1bmipiraw_Scene_Capture \
    libCamera_pbrogc02m1bmipiraw_Scene_Preview \
    libCamera_pbrohi1631qmipiraw_E2EHDR_Preview \
    libCamera_pbrohi1631qmipiraw_E2EHDR_Video \
    libCamera_pbrohi1631qmipiraw_Face_Capture \
    libCamera_pbrohi1631qmipiraw_Flash_Capture \
    libCamera_pbrohi1631qmipiraw_HDR_Capture \
    libCamera_pbrohi1631qmipiraw_HDR_Preview \
    libCamera_pbrohi1631qmipiraw_HDR_Video \
    libCamera_pbrohi1631qmipiraw_N3D_Capture \
    libCamera_pbrohi1631qmipiraw_N3D_Preview \
    libCamera_pbrohi1631qmipiraw_N3D_Video \
    libCamera_pbrohi1631qmipiraw_P1_YUV \
    libCamera_pbrohi1631qmipiraw_Scene_Capture \
    libCamera_pbrohi1631qmipiraw_Scene_Capture_4cell \
    libCamera_pbrohi1631qmipiraw_Scene_Preview \
    libCamera_pbrohi1631qmipiraw_Scene_Preview_4k \
    libCamera_pbrohi1631qmipiraw_Scene_Preview_ZSD_Flash \
    libCamera_pbrohi1631qmipiraw_Video_1080 \
    libCamera_pbrohi1631qmipiraw_Video_1080_60 \
    libCamera_pbrohi1631qmipiraw_Video_4k \
    libCamera_pbroov02b1bmipiraw_E2EHDR_Preview \
    libCamera_pbroov02b1bmipiraw_E2EHDR_Video \
    libCamera_pbroov02b1bmipiraw_Face_Capture \
    libCamera_pbroov02b1bmipiraw_Flash_Capture \
    libCamera_pbroov02b1bmipiraw_HDR_Capture \
    libCamera_pbroov02b1bmipiraw_HDR_Preview \
    libCamera_pbroov02b1bmipiraw_HDR_Video \
    libCamera_pbroov02b1bmipiraw_N3D_Capture \
    libCamera_pbroov02b1bmipiraw_N3D_Preview \
    libCamera_pbroov02b1bmipiraw_N3D_Video \
    libCamera_pbroov02b1bmipiraw_P1_YUV \
    libCamera_pbroov02b1bmipiraw_Scene_Capture \
    libCamera_pbroov02b1bmipiraw_Scene_Capture_4cell \
    libCamera_pbroov02b1bmipiraw_Scene_Preview \
    libCamera_pbroov02b1bmipiraw_Scene_Preview_4k \
    libCamera_pbroov02b1bmipiraw_Scene_Preview_ZSD_Flash \
    libCamera_pbroov02b1bmipiraw_Video_1080 \
    libCamera_pbroov02b1bmipiraw_Video_1080_60 \
    libCamera_pbroov02b1bmipiraw_Video_4k \
    libCamera_pbros5kjn1mipiraw_E2EHDR_Preview \
    libCamera_pbros5kjn1mipiraw_E2EHDR_Video \
    libCamera_pbros5kjn1mipiraw_Face_Capture \
    libCamera_pbros5kjn1mipiraw_Flash_Capture \
    libCamera_pbros5kjn1mipiraw_HDR_Capture \
    libCamera_pbros5kjn1mipiraw_HDR_Preview \
    libCamera_pbros5kjn1mipiraw_HDR_Video \
    libCamera_pbros5kjn1mipiraw_N3D_Capture \
    libCamera_pbros5kjn1mipiraw_N3D_Preview \
    libCamera_pbros5kjn1mipiraw_N3D_Video \
    libCamera_pbros5kjn1mipiraw_P1_YUV \
    libCamera_pbros5kjn1mipiraw_Scene_Capture \
    libCamera_pbros5kjn1mipiraw_Scene_Capture_4cell \
    libCamera_pbros5kjn1mipiraw_Scene_Preview \
    libCamera_pbros5kjn1mipiraw_Scene_Preview_4k \
    libCamera_pbros5kjn1mipiraw_Scene_Preview_ZSD_Flash \
    libCamera_pbros5kjn1mipiraw_Video_1080 \
    libCamera_pbros5kjn1mipiraw_Video_1080_60 \
    libCamera_pbros5kjn1mipiraw_Video_4k \
    libCamera_s5kjn1mipiraw_Boken_Capture \
    libCamera_s5kjn1mipiraw_Capture_Zoom1 \
    libCamera_s5kjn1mipiraw_Capture_Zoom2 \
    libCamera_s5kjn1mipiraw_FaceBeauty \
    libCamera_s5kjn1mipiraw_Flash_Capture \
    libCamera_s5kjn1mipiraw_NHDR_0EV \
    libCamera_s5kjn1mipiraw_Preview_Zoom1 \
    libCamera_s5kjn1mipiraw_Preview_Zoom2 \
    libCamera_s5kjn1mipiraw_Pro_scene \
    libCamera_s5kjn1mipiraw_Resolution \
    libCamera_s5kjn1mipiraw_Resolution_zoom \
    libCamera_s5kjn1mipiraw_Scene_Capture \
    libCamera_s5kjn1mipiraw_Scene_Capture_4cell \
    libCamera_s5kjn1mipiraw_Scene_Preview \
    libCamera_s5kjn1mipiraw_ShortVideo \
    libCamera_s5kjn1mipiraw_SuperNight \
    libCamera_s5kjn1mipiraw_Video \
    libCamera_s5kjn1mipiraw_Video_120fps \
    libCamera_s5kjn1mipiraw_Video_240fps \
    libCamera_s5kjn1mipiraw_Video_EIS \
    libCamera_s5kjn1mipiraw_Video_Zoom1 \
    libCamera_s5kjn1mipiraw_Video_Zoom2 \
    libDR \
    libDefaultFpsActor \
    libFrameRecord \
    libImageEval \
    libJpgEncPipe \
    libNoFpsActor \
    libNvLutEffect_arm64-v8a \
    libOpenCL \
    libSQLiteModule_VER_ALL \
    libSonyIMX230PdafLibrary \
    libSonyIMX230PdafLibraryWrapper \
    libSonyIMX338PdafLibrary \
    libSonyIMX338PdafLibraryWrapper \
    libSonyIMX386PdafLibrary \
    libSonyIMX386PdafLibraryWrapper \
    libSonyIMX519PdafLibrary \
    libSonyIMX519PdafLibraryWrapper \
    libTranASD \
    libTranArcFilter \
    libTranArcHDR \
    libTranArcLLHDR \
    libTranArcLowLight \
    libTranArcNightHawk \
    libTranDenoise \
    libTranExtImgProc \
    libTranEyeDetect \
    libTranFaceBeauty \
    libTranGenderDetect \
    libTranHumanLight \
    libTranMSFilter \
    libTranMagicSky \
    libTranMegDualDepth \
    libTranMegDualDepthtoBokeh \
    libTranMegDualRefocus \
    libTranPlatHW \
    libTranSTPRRepair \
    libTranSTSingleBlur \
    libTranSlimBody \
    libTranSmartDetection \
    libTranStSuperResolution \
    libTran_Log \
    libTran_mtkPowerAPI \
    libWaterMarkProc \
    lib_bsscore \
    lib_iir \
    lib_speech_enh \
    lib_sr_indep_ocl \
    libaaa_ltm \
    libaaa_ltmx \
    libaal_cust \
    libaal_key \
    libaal_mtk \
    libaalservice \
    libaiawb_moon \
    libaiawb_moon_model \
    libaiawb_p1ggm \
    libaiawb_sun \
    libaiawb_sun_model \
    libalsautils-v32 \
    libamipengine \
    libanc_dc_base \
    libanc_hdr \
    libancbase \
    libancbase_848 \
    libapmonitor_vendor \
    libappgamepq \
    libapu_mdw \
    libapusys \
    libapusys_edma \
    libarcsoft_beautyshot \
    libarcsoft_high_dynamic_range \
    libarcsoft_low_light_hdr \
    libarcsoft_low_light_shot \
    libarcsoft_night_hawk \
    libarmnn \
    libarmnn_ndk.mtk.vndk \
    libasn1c_core \
    libasn1c_mapi \
    libasn1c_mdmi \
    libbluetooth_mtk \
    libbluetooth_mtk_pure \
    libbt-vendor \
    libcalculatesharpness \
    libcam.afhal \
    libcam.chdr \
    libcam.feature_utils \
    libcam.hal3a.cctsvr \
    libcam.hal3a.log \
    libcam.hal3a.v3.ae \
    libcam.hal3a.v3.ai3a \
    libcam.hal3a.v3.awb \
    libcam.hal3a.v3.dng \
    libcam.hal3a.v3.fsmgr \
    libcam.hal3a.v3.lscMgr \
    libcam.hal3a.v3.lsctbl.50 \
    libcam.hal3a.v3.nvram.50 \
    libcam.hal3a.v3.platform \
    libcam.hal3a.v3.resultpool \
    libcam.hal3a.v3 \
    libcam.halisp.buf \
    libcam.halisp.common \
    libcam.halisp \
    libcam.halsensor.hwintegration \
    libcam.halsensor \
    libcam.iopipe \
    libcam.isptuning \
    libcam.pdtblgen \
    libcam.seninfn3d \
    libcam.tuning.cache \
    libcam.utils.sensorprovider \
    libcam.vhdr \
    libcam3_tranelapsedtime \
    libcam3_tranpriorityctrl \
    libcam3_transerverengine \
    libcamalgo.3dnr \
    libcamalgo.dngop \
    libcamalgo.eis \
    libcamalgo.fdft \
    libcamalgo.fsc \
    libcamalgo.gyro \
    libcamalgo.ispfeature \
    libcamalgo.lmv \
    libcamalgo.lsc \
    libcamalgo.mfnr \
    libcamalgo.nr \
    libcamalgo.platform \
    libcamalgo.platform2 \
    libcamalgo.utility \
    libcamalgo.warp \
    libcamdrv_imem \
    libcamdrv_isp \
    libcamdrv_tuning_mgr \
    libcamdrv_twin \
    libcamera.custom.pd_buf_mgr \
    libcamera.customae \
    libcamera.customaf \
    libcamera.customawb \
    libcamera.customflk \
    libcameracustom.camera.3a \
    libcameracustom.camera.isp \
    libcameracustom.camera.sensors \
    libcameracustom.camera_exif \
    libcameracustom.eis \
    libcameracustom.flashlight \
    libcameracustom.lens \
    libcameracustom.plugin \
    libcameracustom \
    libcapctrl \
    libcares_naptr \
    libcarrierconfig \
    libccci_util \
    libcharon-ss \
    libchromanr \
    libcmdl \
    libcmdl_ndk.mtk.vndk \
    libcodec2_mtk_c2store \
    libcodec2_mtk_vdec \
    libcodec2_mtk_venc \
    libcodec2_soft_mtk_alacdec \
    libcodec2_soft_mtk_apedec \
    libcodec2_soft_mtk_imaadpcmdec \
    libcodec2_soft_mtk_mp3dec \
    libcodec2_soft_mtk_msadpcmdec \
    libcodec2_vpp_qt_plugin \
    libcodec2_vpp_rs_plugin \
    libcomposer_ext \
    libconnfem \
    libcs_cs35l45_intf \
    libdenoise \
    libdip_drv \
    libdip_imem \
    libdip_postproc \
    libdre \
    libeffecthal.base \
    libeyedetector \
    libfacesattribute \
    libfeature.face \
    libfeature.stereo.provider \
    libfeature_3dnr \
    libfeature_eis \
    libfeature_fsc \
    libfeature_lmv \
    libfeature_rss \
    libfeatureiodrv_mem \
    libforkexecwrap \
    libformatter \
    libfp_ext_svc2 \
    libfsmaudio \
    libgamehdr \
    libged \
    libgpu_aux \
    libgpud \
    libgralloc_extra \
    libgralloc_metadata \
    libgralloctypes_mtk \
    libhdrvideo \
    libheichal \
    libhwm \
    libhydra \
    libifcutils_mtk \
    libimagebuffer_wrapper \
    libimageio \
    libimageio_plat_drv \
    libimageio_plat_pipe \
    libjpeg-alpha-oal_vendor \
    libjpeg-alpha_vendor \
    libkmsetkey \
    libksensor \
    liblpcnr \
    libm4u \
    libmagicsky_64 \
    libmfllcore \
    libmipc \
    libmmagent \
    libmml \
    libmnetlink_v104 \
    libmnl \
    libmpbase \
    libmsbc_mtk \
    libmsnr \
    libmtk-fusion-ril-prop-vsim \
    libmtk-ril \
    libmtkares \
    libmtkcam.atmseventmgr \
    libmtkcam.eventcallback \
    libmtkcam.featurepipe.capture \
    libmtkcam.featurepipe.streaming \
    libmtkcam.featurepipe.vsdof_util \
    libmtkcam.logicalmodule \
    libmtkcam_3rdparty.core \
    libmtkcam_3rdparty.customer \
    libmtkcam_3rdparty.mtk \
    libmtkcam_3rdparty \
    libmtkcam_calibration_convertor \
    libmtkcam_calibration_provider \
    libmtkcam_debugutils \
    libmtkcam_device3_app \
    libmtkcam_device3_hal \
    libmtkcam_device3_hidl \
    libmtkcam_device3_hidlutils \
    libmtkcam_device3_utils \
    libmtkcam_devicesessionpolicy \
    libmtkcam_diputils \
    libmtkcam_exif \
    libmtkcam_fdvt \
    libmtkcam_featurepolicy \
    libmtkcam_featureutils \
    libmtkcam_fwkutils \
    libmtkcam_grallocutils \
    libmtkcam_hwnode \
    libmtkcam_hwutils \
    libmtkcam_imgbuf \
    libmtkcam_mapping_mgr \
    libmtkcam_metadata \
    libmtkcam_metastore \
    libmtkcam_mfb \
    libmtkcam_modulefactory_aaa \
    libmtkcam_modulefactory_custom \
    libmtkcam_modulefactory_drv \
    libmtkcam_modulefactory_utils \
    libmtkcam_modulehelper \
    libmtkcam_pipeline \
    libmtkcam_pipeline_fbm \
    libmtkcam_pipelinemodel \
    libmtkcam_pipelinemodel_adapter \
    libmtkcam_pipelinemodel_capture \
    libmtkcam_pipelinemodel_isp \
    libmtkcam_pipelinemodel_session \
    libmtkcam_pipelinemodel_utils \
    libmtkcam_pipelinemodel_zsl \
    libmtkcam_pipelinepolicy-aov \
    libmtkcam_pipelinepolicy-security \
    libmtkcam_pipelinepolicy-smvr \
    libmtkcam_pipelinepolicy \
    libmtkcam_pipelinepolicy_factory \
    libmtkcam_prerelease \
    libmtkcam_rsc \
    libmtkcam_scenariorecorder \
    libmtkcam_stdutils \
    libmtkcam_streamutils \
    libmtkcam_synchelper \
    libmtkcam_sysutils \
    libmtkcam_tuning_utils \
    libmtkcam_ulog \
    libmtkconfig \
    libmtkconfigutils \
    libmtkhardware_legacy \
    libmtkisp_metadata \
    libmtkmipc-ril \
    libmtknetcap \
    libmtknetutils \
    libmtkrilutils \
    libmtksysutils \
    libmtktinyxml \
    libmtkutils \
    libneuroeara \
    libneuron_adapter \
    libneuron_platform \
    libneuropilot_hal_utils \
    libnir_neon_driver_ndk.mtk.vndk \
    libnxp_extamp_intf \
    liboemcrypto \
    libpixelflinger \
    libportrait_repair_ppl3_ocl \
    libpq_cust_base \
    libpqframework \
    libpqparamparser \
    libratconfig \
    libremosaic_wrapper \
    libremosaiclib \
    librgbwlightsensor \
    librilfusion \
    librmsclib1 \
    librt_extamp_intf \
    libscltm \
    libsdk_sr \
    libsegmention \
    libsegmentionPre \
    libsensor_custom \
    libsimaka \
    libsmartdetector \
    libspeech_enh_lib \
    libspeechparser_vendor \
    libst_mobile \
    libst_sr_models \
    libstblur_capture_api \
    libstereoinfoaccessor_vsdof \
    libstorage_otp \
    libstrongswan \
    libsysenv \
    libtf_asd_lib \
    libtflite_mtk \
    libtflite_native_gainference \
    libtflite_native_inference \
    libtflite_native_seginference \
    libtlcWidevineModularDrm \
    libtranlog \
    libtranssion_beauty \
    libtranssion_bodybeauty \
    libtranssion_cal \
    libtrm \
    libudf \
    liburee_meta_drmkeyinstall \
    libvia-ril \
    libviamipc-ril \
    libvpu5 \
    libwa_depth \
    libwa_dof \
    libwa_refocus \
    libwa_rtdof \
    libwifi-hal-mtk \
    libwo \
    libwpfa \
    libwvhidl \
    libdrmclearkeyplugin \
    libwvdrmengine \
    libdpframework \
    libnir_neon_driver \
    libpq_prot \
    libmtkcam_streaminfo_plugin-p1stt \
    ov02b1b_mipi_raw_IdxMgr \
    ov02b1b_mipi_raw_tuning \
    pblcgc02m1b_mipi_raw_IdxMgr \
    pblcgc02m1b_mipi_raw_tuning \
    pblchi1631q_mipi_raw_IdxMgr \
    pblchi1631q_mipi_raw_tuning \
    pblcov02b1b_mipi_raw_IdxMgr \
    pblcov02b1b_mipi_raw_tuning \
    pblcs5kjn1_mipi_raw_IdxMgr \
    pblcs5kjn1_mipi_raw_tuning \
    pbrogc02m1b_mipi_raw_IdxMgr \
    pbrogc02m1b_mipi_raw_tuning \
    pbrohi1631q_mipi_raw_IdxMgr \
    pbrohi1631q_mipi_raw_tuning \
    pbroov02b1b_mipi_raw_IdxMgr \
    pbroov02b1b_mipi_raw_tuning \
    pbros5kjn1_mipi_raw_IdxMgr \
    pbros5kjn1_mipi_raw_tuning \
    s5kjn1_mipi_raw_IdxMgr \
    s5kjn1_mipi_raw_tuning \
    vendor.fpsensor.hardware.fpsensorhidlsvc@2.0 \
    vendor.mediatek.hardware.apmonitor@2.0 \
    vendor.mediatek.hardware.apuware.utils@2.0 \
    vendor.mediatek.hardware.camera.atms@1.0 \
    vendor.mediatek.hardware.camera.bgservice@1.0 \
    vendor.mediatek.hardware.camera.bgservice@1.1 \
    vendor.mediatek.hardware.camera.ccap@1.0 \
    vendor.mediatek.hardware.camera.frhandler@1.0 \
    vendor.mediatek.hardware.camera.isphal@1.0 \
    vendor.mediatek.hardware.camera.isphal@1.1 \
    vendor.mediatek.hardware.camera.lomoeffect@1.0 \
    vendor.mediatek.hardware.camera.postproc@1.0 \
    vendor.mediatek.hardware.camera.security@1.0 \
    vendor.mediatek.hardware.clientapi@1.0 \
    vendor.mediatek.hardware.composer_ext@1.0 \
    vendor.mediatek.hardware.engineermode@1.0 \
    vendor.mediatek.hardware.engineermode@1.1 \
    vendor.mediatek.hardware.engineermode@1.2 \
    vendor.mediatek.hardware.engineermode@1.3 \
    vendor.mediatek.hardware.mmagent@1.0 \
    vendor.mediatek.hardware.mmagent@1.1 \
    vendor.mediatek.hardware.mms@1.0 \
    vendor.mediatek.hardware.mms@1.1 \
    vendor.mediatek.hardware.mms@1.2 \
    vendor.mediatek.hardware.mms@1.3 \
    vendor.mediatek.hardware.mms@1.4 \
    vendor.mediatek.hardware.mms@1.5 \
    vendor.mediatek.hardware.mms@1.6 \
    vendor.mediatek.hardware.mtkradioex@2.0 \
    vendor.mediatek.hardware.mtkradioex@3.0 \
    vendor.mediatek.hardware.netdagent@1.0 \
    vendor.mediatek.hardware.nvram@1.0 \
    vendor.mediatek.hardware.nvram@1.1 \
    vendor.mediatek.hardware.power@1.1 \
    vendor.mediatek.hardware.power@2.0 \
    vendor.mediatek.hardware.pq@2.0 \
    vendor.mediatek.hardware.pq@2.1 \
    vendor.mediatek.hardware.pq@2.10 \
    vendor.mediatek.hardware.pq@2.11 \
    vendor.mediatek.hardware.pq@2.12 \
    vendor.mediatek.hardware.pq@2.13 \
    vendor.mediatek.hardware.pq@2.14 \
    vendor.mediatek.hardware.pq@2.15 \
    vendor.mediatek.hardware.pq@2.2 \
    vendor.mediatek.hardware.pq@2.3 \
    vendor.mediatek.hardware.pq@2.4 \
    vendor.mediatek.hardware.pq@2.5 \
    vendor.mediatek.hardware.pq@2.6 \
    vendor.mediatek.hardware.pq@2.7 \
    vendor.mediatek.hardware.pq@2.8 \
    vendor.mediatek.hardware.pq@2.9 \
    vendor.mediatek.hardware.videotelephony@1.0 \
    vendor.transsion.hardware.trancam.trancamserver@1.0 \
    libArcFilter \
    libNvStreamingSdkCore \
    libarcsoft_frc \
    libaudiotoolkit \
    libc++_shared \
    libcvface_api \
    libeffect \
    libiconv \
    libjniarcsoft_frc \
    libzbar \
    EngineerMode \
    android.hardware.neuralnetworks@1.3-service-mtk-gpu.xml \
    android.hardware.usb@1.2-service-mediatekv2.xml \
    gnss-mediatek.xml \
    gnss@2.1-service.xml \
    manifest_android.hardware.drm@1.4-service.widevine.xml \
    manifest_media_c2_V1_1_mediatek.xml \
    vendor.transsion.hardware.trancam.trancamserver@1.0.xml \
    bip \
    ccci_mdinit \
    ccci_rpcd \
    charon \
    epdg_wod \
    fuelgauged \
    fuelgauged_nvram \
    gsm0710muxd \
    android.hardware.drm@1.4-service.widevine \
    android.hardware.gnss-service.mediatek \
    android.hardware.graphics.allocator@4.0-service-mediatek \
    android.hardware.keymaster@4.1-service.trustonic \
    android.hardware.media.c2@1.2-mediatek-64b \
    android.hardware.neuralnetworks@1.3-service-mtk-neuron \
    android.hardware.secure_element@1.2-service-mediatek \
    android.hardware.usb@1.2-service-mediatekv2 \
    camerahalserver \
    mtkfusionrild \
    tetheroffloadservice \
    vendor.mediatek.hardware.keymaster_attestation@1.1-service \
    vendor.mediatek.hardware.mmagent@1.1-service \
    vendor.mediatek.hardware.mms@1.6-service \
    vendor.mediatek.hardware.nvram@1.1-service \
    vendor.mediatek.hardware.pq@2.2-service \
    vendor.transsion.hardware.trancam.trancamserver@1.0-service \
    vtservice_hidl \
    init.insmod \
    ipsec_mon \
    lib3a.ccu.ddr \
    lib3a.ccu.dm \
    lib3a.ccu.pm \
    mcDriverDaemon \
    mnld \
    mt6660_calibration \
    mtk_agpsd \
    netdagent \
    nvram_daemon \
    rt5512_calibration \
    starter \
    stroke \
    thermal \
    thermal_manager \
    thermalloadalgod \
    volte_imcb \
    volte_imsm_93 \
    volte_md_status \
    volte_stack \
    volte_ua \
    vpud \
    wfca \
    wlan_assistant \
    wmt_launcher \
    wmt_loader \
    xcap

PRODUCT_PACKAGES += \
    vendor_lib_libmtk_drvb_so \
    vendor_lib64_hw_vulkan_mt6781_so \
    vendor_lib64_hw_kmsetkey_default_so \
    vendor_lib64_hw_gatekeeper_trustonic_so \
    vendor_lib64_hw_gatekeeper_default_so \
    vendor_lib64_libdpframework_so \
    vendor_lib64_libmtk_drvb_so \
    vendor_lib64_libnir_neon_driver_so \
    vendor_lib64_libpq_prot_so
